Run tests in pre-commit hook

diff --git a/dev/hooks/pre-commit b/dev/hooks/pre-commit
--- a/dev/hooks/pre-commit
+++ b/dev/hooks/pre-commit
@@ -15,4 +15,12 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+echo "Running tests..."
+pytest -rP
+
+if [ $? -ne 0 ]; then
+    echo "** ERROR: Tests failed. Commit aborted. **"
+    exit 1
+fi
+
 exit 0
